-- Exact source JSON fields are stored as individual SQLite columns.
CREATE TABLE IF NOT EXISTS psp_student_data (
  "_id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "S.No." TEXT,
  "Session" TEXT,
  "Student NIC ID" TEXT,
  "SR No." TEXT,
  "Aadhar Number" TEXT,
  "Student Name" TEXT,
  "Father Name" TEXT,
  "Mother Name" TEXT,
  "DOB" TEXT,
  "Gender" TEXT,
  "Social Category" TEXT,
  "Religion" TEXT,
  "Mother Tongue" TEXT,
  "Rural/Urban" TEXT,
  "Date of Admission" TEXT,
  "Admission Number/SR No" TEXT,
  "Belong To BPL" TEXT,
  "Belong to Disadvantaged Group" TEXT,
  "Getting Free Education" TEXT,
  "Studying in Class" TEXT,
  "Class Studied in Prev. Year" TEXT,
  "If in Class 1, Status of Previous Year" TEXT,
  "Days child attended school (in the prev. year)" TEXT,
  "Medium of Instruction" TEXT,
  "Type of Disablity" TEXT,
  "Facilities received by CWSN" TEXT,
  "No. Of Uniform Sets" TEXT,
  "Free Text Books" TEXT,
  "Free Transport" TEXT,
  "Free Escort" TEXT,
  "MDM Beneficiary" TEXT,
  "Free Hostel Facility" TEXT,
  "Child attended Special Training" TEXT,
  "In Last Examination Appeard" TEXT,
  "In Last Examination Passed" TEXT,
  "Stream (Grades 11 & 12)" TEXT,
  "Trade/Sector (Grades 9 to 12)" TEXT,
  "Iron & Folic Acid Tablets" TEXT,
  "Deworming Tablets" TEXT,
  "Vitamin-A Supplement" TEXT,
  "Mobile Number" TEXT,
  "Habitation or Locality" TEXT,
  "In Last Examination % Marks" TEXT,
  "Email Address" TEXT
);
CREATE TABLE IF NOT EXISTS udise_data (
  "_id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "studentId" TEXT,
  "studentCodeNat" TEXT,
  "studentCodeState" TEXT,
  "schoolId" TEXT,
  "studentName" TEXT,
  "gender" TEXT,
  "genderDesc" TEXT,
  "socCatId" TEXT,
  "socialCategoryList" TEXT,
  "socialCategoryDesc" TEXT,
  "minorityId" TEXT,
  "minorityDesc" TEXT,
  "uuid" TEXT,
  "uuidMasked" TEXT,
  "isUuidAvailable" TEXT,
  "isValidUuid" TEXT,
  "nameAsUuid" TEXT,
  "uuidStatus" TEXT,
  "uuidStatusDesc" TEXT,
  "uuidValidateRemarks" TEXT,
  "uuidValidateDate" TEXT,
  "dob" TEXT,
  "guardianName" TEXT,
  "fatherName" TEXT,
  "motherName" TEXT,
  "address" TEXT,
  "pincode" TEXT,
  "primaryMobile" TEXT,
  "secondaryMobile" TEXT,
  "isBplYN" TEXT,
  "aayBplYN" TEXT,
  "ewsYN" TEXT,
  "cwsnYN" TEXT,
  "natIndYN" TEXT,
  "natOtherCountry" TEXT,
  "motherTongue" TEXT,
  "motherTongueDesc" TEXT,
  "email" TEXT,
  "acYearId" TEXT,
  "lastYearId" TEXT,
  "lastYearIdDesc" TEXT,
  "classId" TEXT,
  "classDesc" TEXT,
  "classPyId" TEXT,
  "classPyDesc" TEXT,
  "sectionDesc" TEXT,
  "sectionPyDesc" TEXT,
  "sectionId" TEXT,
  "impairmentType" TEXT,
  "disabilityCerti" TEXT,
  "impairmentPercent" TEXT,
  "ooscYN" TEXT,
  "ooscMainstreamedYN" TEXT,
  "profileStatus" TEXT,
  "formStatus" TEXT,
  "ageCheckSkipped" TEXT,
  "academicStreamDesc" TEXT,
  "admnNumber" TEXT,
  "isRepeater" TEXT,
  "inactiveDate" TEXT,
  "statusId" TEXT,
  "statusDesc" TEXT,
  "statusL1Id" TEXT,
  "statusL1Desc" TEXT,
  "statusL2Id" TEXT,
  "statusL2Desc" TEXT,
  "isNew" TEXT,
  "bloodGroup" TEXT,
  "bloodGroupDesc" TEXT,
  "deleteReason" TEXT,
  "deleteReasonDesc" TEXT,
  "schUdiseCode" TEXT,
  "schoolName" TEXT,
  "yearId" TEXT,
  "studentMovType" TEXT,
  "lastModifiedOn" TEXT,
  "lastModifiedBy" TEXT,
  "apaarIdStatus" TEXT,
  "apaarId" TEXT,
  "apaarIdStatusDesc" TEXT,
  "schoolPY" TEXT,
  "mbuStatusDesc" TEXT,
  "examFormStatus" TEXT,
  "nameChangeCountTotal" TEXT,
  "nameChangeCountAdmin" TEXT,
  "nameChangeCountSchool" TEXT
);
CREATE TABLE IF NOT EXISTS student_remarks (
  "remark_id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "psp_nic" TEXT,
  "udise_pen" TEXT,
  "remark" TEXT DEFAULT '',
  "review_status" TEXT DEFAULT 'PENDING',
  "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_remark_psp ON student_remarks(psp_nic);
CREATE INDEX IF NOT EXISTS idx_remark_udise ON student_remarks(udise_pen);

-- Speed up PSP lookups and data mapping
CREATE UNIQUE INDEX IF NOT EXISTS idx_psp_nic ON psp_student_data ("Student NIC ID");
CREATE INDEX IF NOT EXISTS idx_psp_matching_fields ON psp_student_data ("Aadhar Number", "Student Name", "Studying in Class");

-- Speed up UDISE lookups and tracking data
CREATE UNIQUE INDEX IF NOT EXISTS idx_udise_id ON udise_data (studentId);
CREATE INDEX IF NOT EXISTS idx_udise_pen ON udise_data (studentCodeNat);
CREATE INDEX IF NOT EXISTS idx_udise_matching_fields ON udise_data (uuid, studentName, classId, classDesc);

-- Speed up audit remarks resolution
CREATE INDEX IF NOT EXISTS idx_remarks_lookup ON student_remarks (psp_nic, udise_pen);

CREATE INDEX IF NOT EXISTS idx_psp_class ON psp_student_data ("Studying in Class");
CREATE INDEX IF NOT EXISTS idx_udise_class_id ON udise_data (classId);
CREATE INDEX IF NOT EXISTS idx_udise_class_desc ON udise_data (classDesc);
